config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :github_repos, except: ['new', 'index', 'show']
get 'projects/:id/github_repos/new', to: 'github_repos#new_in_project', as: 'new_github_repo'
get 'projects/:id/github_repos', to: 'github_repos#index_in_project', as: 'index_github_repos'

app/models/github_repo.rb
class GithubRepo < ActiveRecord::Base
  unloadable

  belongs_to :project
  has_many :issues

  attr_accessible :project_id, :name, :owner, :user, :pass
  validates :project_id, presence: true
  validates :name, presence: true
  validates :owner, presence: true

  validate :github_auth?

  def github_auth?
    uri = URI.parse("https://api.github.com")
    https = Net::HTTP.new(uri.host, uri.port)
    https.use_ssl = true
    https.verify_mode = OpenSSL::SSL::VERIFY_NONE
    request = Net::HTTP::Get.new("/repos/#{owner}/#{name}")
    request.basic_auth(user, pass)

    response = https.request(request)
    unless response.code == "200"
      errors.add(:data, "seems to be wrong. We couldn't access to the github repository")
    end
  end
end

app/controllers/github_repos_controller.rb
class GithubReposController < ApplicationController
  unloadable

  def new_in_project
    @project = Project.find(params[:id])
    @github_repo = @project.github_repos.build
  end

  def create
    @github_repo = GithubRepo.new(github_repo_params)
    if @github_repo.save
      redirect_to index_github_repos_path(@github_repo.project)
    else
      render :action => 'new_in_project'
    end
  end

  def index_in_project
    @project = Project.find(params[:id])
    @github_repos = @project.github_repos
    render template: 'github_repos/index'
  end

  def edit
    @github_repo = GithubRepo.find(params[:id])
    @project = @github_repo.project
  end

  def update
    @github_repo = GithubRepo.find(params[:id])
    @github_repo.update(github_repo_params)
    redirect_to index_github_repos_path(@github_repo.project)
  end

  def destroy
    @github_repo = GithubRepo.find(params[:id])
    @project = @github_repo.project
    @github_repo.destroy
    redirect_to index_github_repos_path(@project)
  end

  private
    def github_repo_params
      params.require(:github_repo).permit(:project_id, :name, :owner, :user, :pass)
    end
end

app/helpers/github_repos_helper.rb
module GithubReposHelper
end

app/views/github_repos/_form.html.erb
<%= f.hidden_field :project_id %>
<p><%= f.text_field :name, size: 80, maxlength: 255, required: true, label: l(:repository_name_on_github) %></p>
<p><%= f.text_field :owner, size: 80, maxlength: 255, required: true, label: l(:repository_owner_on_github) %></p>
<p><%= f.text_field :user, size: 80, maxlength: 255, required: true, label: l(:username_accessing_to_github) %></p>
<p><%= f.password_field :pass, size: 80, maxlength: 255, required: true, label: l(:password_accessing_to_github) %></p>

app/views/github_repos/edit.html.erb
<h3><%= l(:button_edit) %></h3>
<%= labelled_form_for @github_repo, url: github_repo_path(@github_repo), html: {method: :put, id: 'github_repo-form', multipart: true} do |f| %>
  <div class="box tabular">
    <div id="all_attributes">
      <%= render :partial => 'github_repos/form', :locals => {:f => f} %>
    </div>
  </div>
  <%= submit_tag l(:button_submit) %>
<% end %>

app/views/github_repos/index.html.erb
<div class="autoscroll">
  <table class="list">
    <thead>
      <tr>
        <th>name</th>
        <th>owner</th>
        <th>username</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% for repo in @github_repos %>
        <tr>
          <td><%= repo.name %></td>
          <td><%= repo.owner %></td>
          <td><%= repo.user %></td>
          <td class="buttons">
            <%= link_to(l(:button_edit), edit_github_repo_path(repo), :class => 'icon icon-edit') %>
            <%= delete_link github_repo_path(repo) %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<p>
<%= link_to(l(:create_new_github_repo),
            new_github_repo_path(@project),
            :class => 'icon icon-add') %>
</p>

app/views/github_repos/new_in_project.html.erb
<%= title l(:new_github_repo) %>

<%= labelled_form_for @github_repo, :html => {:id => 'github_repo-form', :multipart => true} do |f| %>

  <%= error_messages_for 'github_repo' %>

  <div class="box tabular">
    <div id="all_attributes">
      <%= render :partial => 'github_repos/form', :locals => {:f => f} %>
    </div>
  </div>
  <%= submit_tag l(:button_create) %>
<% end %>

app/views/issues/_form_github_repositories.html.erb
<p><%= form.select :github_repo_id, principals_options_for_select(@issue.project.github_repos, @issue.github_repo), :include_blank => true, :required => @issue.required_attribute?('github_repo_id'), :label => l(:github_repo) %></p>

app/views/issues/_show_github_repositories.html.erb
<hr>
<div id="github-repository">
  <span class="github-repo"><%= l(:github_repo) %></span>
  <%= @issue.github_repo.nil? ? "-" : @issue.github_repo.name %>
</div>